### PR TITLE
Update python and GitHub actions in workflow

### PR DESCRIPTION
**Pull request by SpencerIsGiddy**
Updates python to 3.11 from 3.6 and updates actions checkout and python to v3 and v4

### CODE REVIEW

**Comment by rossengeorgiev** [comment]
version `3.10` needs to be specified as a string, otherwise `yaml` parses it as a float resulting in `3.1`.

**Comment by GiddyGoatGaming** [comment]
> version `3.10` needs to be specified as a string, otherwise `yaml` parses it as a float resulting in `3.1`.

Okay, I think I did what you said

**Comment by Gobot1234** [comment]
> > version `3.10` needs to be specified as a string, otherwise `yaml` parses it as a float resulting in `3.1`.
> 
> Okay, I think I did what you said with the latest commit👍

Whilst what you've done works, I think Rossen meant change this to `"3.10"` (the current version will use the first release of 3.10 forever which doesn't seem desirable)

**Comment by GiddyGoatGaming** [comment]
> > > version `3.10` needs to be specified as a string, otherwise `yaml` parses it as a float resulting in `3.1`.
> > 
> > 
> > Okay, I think I did what you said with the latest commit👍
> 
> Whilst what you've done works, I think Rossen meant change this to `"3.10"` (the current version will use the first release of 3.10 forever which doesn't seem desirable)

Oh I see now! Sorry about that haha. Should be good now

**Pull request closed without merging**
