### PR TITLE
Added shortcut function to send_messages and wait for them.

### PR DESCRIPTION
**Pull request by SleepProgger**
This patch just adds two simple functions to the client to send messages (and jobs) and wait for them.  
This is a really common use case of the client, so it should be as easy as possible to do this.
<hr>
I thought this patch would get a little bit bigger as i though to have seen a response to a message before i had the chance to register for the matching event. But i was NOT able to reproduce this.  
Just in case it will be necessary one day to ensure one does not miss the event, something like this should work:

        result = AsyncResult()
        self.once(response_emsg, result.set)
        self.send(message)
        return result.get(timeout=timeout).body

### CODE REVIEW

**Comment by rossengeorgiev** [comment]
Ok, I'm not so sure these methods are necessary, as I prefer the explicit workflow of sending a message and then registering a callback. It's 2 lines instead of one, but it's very clear and flexible.

> I thought this patch would get a little bit bigger as i though to have seen a response to a message before i had the chance to register for the matching event.

The whole thing is single threaded. Once you are in a block of code, you need to yield to gevent so other code can run. Any blocking operation that requires you to wait, will yield. You can send a message, and then register callbacks.

Your example code can be reduced to the following.

```python
self.send(message)
self.wait_event(emsg, timeout=10)[0].body
```
Although the above has the problem that on timeout `wait_event` will return `None`. 

You are trying to turn request/response into a get. I've been thinking about that before, and I don't think it's a good idea. It may cause more confusion than it's worth. The method names need to also be very clear about what it does. Something like `send_and_wait_event`. 

I also see that you've made them raise on timeout, which I don't like as a default behavior. To properly handle the exception you need to import gevent.Timeout, which adds unnecessary code, unless you specifically need to do it that way, which I found to be rare. 

```python
from gevent import Timeout

try:
    resp = self.wait_event(emsg, timeout=10, raises=True)
except Timeout:
    # do stuff

# versus

resp = self.wait_event(emsg, timeout=10)
if resp is None:
    # do stuff
```

The `try``except` block makes more sense if you need to send/wait for a series of messages.

```python
try:
    self.send(message1)
    resp1, = self.wait_event(emsg, timeout=10, raises=True)
    self.send(message2)
    resp2, = self.wait_event(emsg, timeout=10, raises=True)
    self.send(message3)
    resp3, = self.wait_event(emsg, timeout=10, raises=True)
except Timeout:
    # we failed :(, start over
```
I've yet to see a case where that's necessary.

**Comment by SleepProgger** [comment]
> The whole thing is single threaded. Once you are in a block of code, you need to yield to gevent so other code can run. Any blocking operation that requires you to wait, will yield.

I wasn't absolutely sure if there wasn't an context switch down the line somewhere after sending the message, but it doesn't looks like it.
<hr>
>Ok, I'm not so sure these methods are necessary, as I prefer the explicit workflow of sending a message and then registering a callback.Ok, I'm not so sure these methods are necessary, as I prefer the explicit workflow of sending a message and then registering a callback.

I'd like this shortcut functions because:
The use case to send a request and immediately wait for a response is really common (at least as soon as the lib is used to do something (trading, fetching information on demand, ...)). So having to write 3 lines to do this (without using exceptions) isn't really nice IMHO.
3 lines because wait_event could return None, so one **can't** simple do `foo, = wait_event()` because None is not iterable. So at least something like:
```
foo = wait_event(msg)
if not foo is None:
  foo = foo[0]
```
... would be necessary every time.

IMHO raising an exception for some cases when not receiving the answer is the correct thing to do, as for some requests a missing response IS an exceptional behavior. But i understand that it isn't required all the time, so i'd suggest adding an raise flag to the wait_for_message and wait_for_job functions so it behaves like `wait_event` but always return the message (or None) as a single response (not in a tuple).

You are definetly right about the names:
I'd suggest `send_job_and_wait` and `send_message_and_wait`

> You are trying to turn request/response into a get. I've been thinking about that before, and I don't think it's a good idea. It may cause more confusion than it's worth.

But that is exactly what a bunch of functionality of steam is, you send a request and wait for a response.

**Comment by rossengeorgiev** [comment]
It does indeed simplify the usecase. I'm happy with merging this. Can correct the docs strings and squash the commits?

**Comment by SleepProgger** [comment]
Can do. ETA: some when in the next 24 hours..

**Comment by rossengeorgiev** [comment]
By the way, you can just force push changes onto your branch. It will automatically update the pull request. There is no need to make a new one. The PR is just the difference between the two branches.

**Pull request closed without merging**
