### PR TITLE
Conditionally install enum34 only if Python < 3.4

### PR DESCRIPTION
**Pull request by xfxf**
This allows installation on Python 3.5.  'pip install steam' on 3.5 currently is failing (but works on 3.4).

### CODE REVIEW

**Comment by rossengeorgiev** [comment]
Thanks

226aa4d has been merged and deployed in `0.5.3`

**Comment by xfxf** [comment]
Hi @rossengeorgiev - enum34 appears to have been added back into requirements.txt, which is making 'pip install steam' fail on 3.5.

**Comment by rossengeorgiev** [comment]
`requirements.txt` never makes it to the pip package. It contains dependencies for the source repo only.

Looks like a problem with setuptools. The metadata generated has `enum34`. Ah... I suspect this one will tricky to fix. Google comes up with many results regarding the same issue, but not solution at first glance.

**Comment by rossengeorgiev** [comment]
Please try `0.5.4` from `pip` and tell me if it installs correctly under py35. Thanks

**Comment by xfxf** [comment]
Hello, seems to install fine now, thanks!

**Pull request closed without merging**
